# FaceBoxes: A CPU Real-time Face Detector with High Accuracy

#### Rapidly Digested Convolu- tional Layers (RDCL)
RDCL：快速消除卷积层，确保Faceboxes在CPU的设备上有实时性，主要分一下三步：
- **Shrinking the spatial size of input**：急降空间纬度大小输入，对于卷积和池化层使用大步伐，Conv1:4，Pool1:2，Conv2:2，Pool2:2，合在一起就降低了32倍。
- **Choosing suitable kernel size**:选择合适的卷积核，卷积核越小卷积计算越快（因为步伐一定的情况下，卷积核越小，计算量越小），但是卷积核越大越空间域的信息丢失越少，Conv1的kernel：7x7，Conv2的kernel：5x5，Pool1的kernel：3x3，Pool2的kernel：3x3。
- **Reducing the number of output channels**:降低输出通道数, 使用c.Relu减少输出通道数

In [5]:
import cv2   
import numpy as np   
from matplotlib import pyplot as plt 

img = cv2.imread('lenna.jpeg')
kernel = np.ones((3,3),np.float32)/25
dst = cv2.filter2D(img,-1,kernel)
print(kernel)
print(dst)

# plt.subplot(121),plt.imshow(img)
# plt.title('Original'),plt.xticks([]),plt.yticks([])
# plt.subplot(122),plt.imshow(dst)
# plt.title('Averaging'),plt.xticks([]),plt.yticks([])
# plt.show()

[[0.04 0.04 0.04]
 [0.04 0.04 0.04]
 [0.04 0.04 0.04]]
[[[39 55 81]
  [38 55 81]
  [38 55 81]
  ...
  [40 54 80]
  [41 56 81]
  [43 59 84]]

 [[38 55 81]
  [38 55 81]
  [38 55 81]
  ...
  [36 50 75]
  [35 49 73]
  [37 51 75]]

 [[38 55 81]
  [38 55 81]
  [37 54 80]
  ...
  [28 39 61]
  [24 35 54]
  [24 34 53]]

 ...

 [[ 7 12 12]
  [ 7 11 12]
  [ 7 11 14]
  ...
  [ 9 20 28]
  [13 22 34]
  [14 24 36]]

 [[ 7 10 13]
  [ 6 10 12]
  [ 7 11 13]
  ...
  [15 24 36]
  [17 26 43]
  [19 28 45]]

 [[ 7 10 12]
  [ 6 10 12]
  [ 7 11 13]
  ...
  [16 26 38]
  [19 28 44]
  [21 30 47]]]
